apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-mysql
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: "root:1234@tcp(localhost:3306)/dapr"